Evenementitineraire:
    type: entity
    table: evenementitineraire
    indexes:
        IDX_ABBE37DDB26681E:
            columns:
                - evenement
    id:
        iditineraire:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
    fields:
        nomitineraire:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    oneToOne:
        evenement:
            targetEntity: Evenement
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                evenement:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
