Image:
    type: entity
    table: image
    indexes:
        fk_image_auteur_idx:
            columns:
                - auteur
        fk_image_1_idx:
            columns:
                - categorie
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        description:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        taille:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        poids:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        path:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        categorie:
            targetEntity: Categorie
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                categorie:
                    referencedColumnName: id
            orphanRemoval: false
        auteur:
            targetEntity: Membre
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                auteur:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
