Role:
    type: entity
    table: role
    uniqueConstraints:
        label_UNIQUE:
            columns:
                - label
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        label:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        niveau:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
