Sortiedecouverte:
    type: entity
    table: sortiedecouverte
    indexes:
        fk_sortiedecouverte_rdv_idx:
            columns:
                - lieurendezvous
        fk_sortiedecouverte_evenement_idx:
            columns:
                - evenement
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        evenement:
            targetEntity: Evenement
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                evenement:
                    referencedColumnName: id
            orphanRemoval: false
        lieurendezvous:
            targetEntity: Lieurendezvous
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                lieurendezvous:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
