site_trail_homepage_empty:
    path:     /
    defaults: { _controller: SiteTrailBundle:Home:index }
site_trail_homepage:
    path:     /home
    defaults: { _controller: SiteTrailBundle:Home:index }
site_trail_map:
    path:     /map
    defaults: { _controller: SiteTrailBundle:Map:index }
site_trail_map_createRoute:
    path:     /map/createRoute
    defaults: { _controller: SiteTrailBundle:Map:createRoute }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout