services:
#    site_trail.example:
#        class: Site\TrailBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    custom_user_provider:
        class: Site\TrailBundle\Security\CustomUserProvider
        arguments: ["@doctrine.orm.entity_manager"]
    itineraire_service:
        class: Site\TrailBundle\Controller\ItiniraireController
    sso_authenticator:
        class: Site\TrailBundle\Security\SSOAuthenticator
        arguments: ["@custom_user_provider"]
    evenement_service:
        class: Site\TrailBundle\Services\EvenementService
        arguments: ["@doctrine.orm.entity_manager"]
    csrf_twig_extension:
        class: Site\TrailBundle\Twig\CsrfTwigExtension
        arguments: ["@form.csrf_provider"]
        tags:
            - { name: twig.extension }