services:
#    site_trail.example:
#        class: Site\TrailBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    custom_user_provider:
        class: Site\TrailBundle\Security\CustomUserProvider
        arguments: ["@doctrine.orm.entity_manager"]
    sso_authenticator:
        class: Site\TrailBundle\Security\SSOAuthenticator
        arguments: ["@custom_user_provider"]