Commentaire:
    type: entity
    table: commentaire
    indexes:
        fk_commentaire_auteur_idx:
            columns:
                - auteur
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        texte:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    manyToOne:
        auteur:
            targetEntity: Membre
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                auteur:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        new:
            targetEntity: News
            cascade: {  }
            mappedBy: commentaire
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
