Evenementdivers:
    type: entity
    table: evenementdivers
    indexes:
        fk_evenementdivers_evenement_idx:
            columns:
                - evenement
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        evenement:
            targetEntity: Evenement
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                evenement:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
