Itineraire:
    type: entity
    table: itineraire
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        trace:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        datecreation:
            type: date
            nullable: false
            comment: ''
        longueur:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        deniveleplus:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        denivelemoins:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        description:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        numero:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        typechemin:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        difficulte:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        status:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        auteur:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
