Membre:
    type: entity
    table: membre
    indexes:
        fk_membre_role_idx:
            columns:
                - role
        fk_membre_avatar_idx:
            columns:
                - avatar
    uniqueConstraints:
        email_UNIQUE:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        datenaissance:
            type: date
            nullable: false
            comment: ''
        telephone:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        licence:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        tokenics:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        role:
            targetEntity: Role
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                role:
                    referencedColumnName: id
            orphanRemoval: false
        avatar:
            targetEntity: Image
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                avatar:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
