News:
    type: entity
    table: news
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        visibilite:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        alias:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        texte:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        auteur:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        date:
            type: date
            nullable: false
            comment: ''
    manyToMany:
        commentaire:
            targetEntity: Commentaire
            cascade: {  }
            mappedBy: null
            inversedBy: new
            joinTable:
                name: commentairenews
                joinColumns:
                    -
                        name: new
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: commentaire
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
