Parcours:
    type: entity
    table: parcours
    indexes:
        fk_parcours_evenement_idx:
            columns:
                - evenement
    id:
        iditineraire:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: idItineraire
    oneToOne:
        evenement:
            targetEntity: Evenement
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                evenement:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
