Participation:
    type: entity
    table: participation
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        etatinscription:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        resultat:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        divers:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
