Participants:
    type: entity
    table: participants
    indexes:
        fk_participants_membre_idx:
            columns:
                - membre
        fk_participants_evenement_idx:
            columns:
                - evenement
        fk_participants_participation_idx:
            columns:
                - participation
    id: {  }
    oneToOne:
        evenement:
            targetEntity: Evenement
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                evenement:
                    referencedColumnName: id
            orphanRemoval: false
        membre:
            targetEntity: Membre
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                membre:
                    referencedColumnName: id
            orphanRemoval: false
    manyToOne:
        participation:
            targetEntity: Participation
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                participation:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
