Permission:
    type: entity
    table: permission
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        label:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    manyToMany:
        role:
            targetEntity: Role
            cascade: {  }
            mappedBy: permission
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
