Programme:
    type: entity
    table: programme
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        label:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        duree:
            type: datetime
            nullable: false
            comment: ''
    lifecycleCallbacks: {  }
